# Dockerfile
#
# VERSION               0.1

FROM debian:jessie-backports

RUN apt-key adv --fetch-keys http://packages.mendix.com/mendix-debian-archive-key.asc
RUN echo "deb http://packages.mendix.com/platform/debian/ jessie main" > /etc/apt/sources.list.d/mendix.list

RUN apt-get update && apt-get install -y --no-install-recommends m2ee-tools openjdk-8-jre-headless postgresql-client procps tree netcat && apt-get clean

RUN useradd -m mendix -b /srv && cd /srv/mendix && mkdir -p .m2ee data model runtimes web data/database data/files data/model-upload data/log data/tmp

COPY start.sh /start.sh
COPY m2ee.yaml /srv/mendix/.m2ee/m2ee.yaml
COPY application.mda /srv/mendix/data/model-upload/application.mda
RUN chmod +x /start.sh

RUN chown -R mendix:mendix /srv/mendix

ENV MXDATA /srv/mendix/data

EXPOSE 8000

ENTRYPOINT ["/start.sh"]

USER mendix
